import type { InteractionRecord, MedicineRecord, SourceRef } from "./types";

// PROTOTYPE REFERENCE DATASET
// Short summaries of widely published patient information (NHS Medicines A–Z,
// US National Library of Medicine MedlinePlus / DailyMed). It is NOT a live or
// clinically reviewed drug database. Replace via MedicineInfoProvider.

const CURATED = "2026-09-26 (prototype curation — not clinically reviewed)";

const nhs = (slug: string): SourceRef => ({ name: "NHS Medicines A–Z", url: `https://www.nhs.uk/medicines/${slug}/` });
const dailymed = (q: string): SourceRef => ({
  name: "DailyMed (US National Library of Medicine)",
  url: `https://dailymed.nlm.nih.gov/dailymed/search.cfm?query=${encodeURIComponent(q)}`,
});

const INACTIVE_NOTE = null; // varies by manufacturer — shown as unavailable

export const MEDICINES: MedicineRecord[] = [
  {
    medicine_id: "paracetamol",
    generic_name: "Paracetamol",
    brand_name: ["Panadol", "Calpol", "Tylenol (as acetaminophen)"],
    aliases: ["paracetamol", "acetaminophen", "pcm", "panadol", "calpol", "tylenol", "crocin", "dolo"],
    active_ingredients: ["Paracetamol (acetaminophen)"],
    inactive_ingredients: INACTIVE_NOTE,
    common_strengths: ["500 mg", "650 mg", "120 mg/5 ml"],
    dosage_forms: ["Tablet", "Capsule", "Oral liquid", "Suppository"],
    therapeutic_class: "Analgesic and antipyretic (pain and fever reliever)",
    indications: ["Mild to moderate pain", "Fever"],
    mechanism: {
      simple: "Helps reduce pain and fever by acting on the brain's pain and temperature-control pathways.",
      detailed:
        "Thought to act mainly in the central nervous system, with weak inhibition of cyclo-oxygenase (COX) enzymes and prostaglandin production, and an effect on the hypothalamic heat-regulating centre. The exact mechanism is not fully understood.",
    },
    common_side_effects: ["Side effects are uncommon when taken as directed"],
    important_side_effects: ["Signs of liver problems, such as yellowing of the skin or eyes"],
    serious_warnings: ["Allergic reaction: rash, swelling of the face or throat, difficulty breathing", "Taking more than the prescribed amount can cause serious liver damage"],
    food_interactions: [],
    alcohol: "Regular heavy alcohol use may increase the risk of liver damage.",
    condition_warnings: ["liver problems", "regular heavy alcohol use", "low body weight"],
    onset_information: "Usually starts to work within about an hour.",
    duration_information: "Effects typically last around 4 to 6 hours.",
    treatment_duration: null,
    sources: [nhs("paracetamol-for-adults"), dailymed("acetaminophen")],
    last_verified_date: CURATED,
  },
  {
    medicine_id: "ibuprofen",
    generic_name: "Ibuprofen",
    brand_name: ["Brufen", "Nurofen", "Advil"],
    aliases: ["ibuprofen", "brufen", "nurofen", "advil", "ibuprofene"],
    active_ingredients: ["Ibuprofen"],
    inactive_ingredients: INACTIVE_NOTE,
    common_strengths: ["200 mg", "400 mg", "600 mg"],
    dosage_forms: ["Tablet", "Capsule", "Oral liquid", "Gel"],
    therapeutic_class: "Non-steroidal anti-inflammatory drug (NSAID)",
    indications: ["Pain", "Inflammation", "Fever"],
    mechanism: {
      simple: "Reduces pain, swelling and fever by lowering chemicals in the body that cause inflammation.",
      detailed: "Non-selective, reversible inhibitor of cyclo-oxygenase enzymes COX-1 and COX-2, reducing prostaglandin synthesis.",
    },
    common_side_effects: ["Indigestion or stomach discomfort", "Nausea", "Headache", "Dizziness"],
    important_side_effects: ["Black or bloody stools", "Swelling of ankles or reduced urine", "Persistent stomach pain"],
    serious_warnings: ["Vomiting blood or material that looks like coffee grounds", "Allergic reaction or asthma worsening", "Chest pain or signs of stroke"],
    food_interactions: ["Often advised to be taken with or after food to reduce stomach upset."],
    alcohol: "Alcohol may increase the risk of stomach irritation and bleeding.",
    condition_warnings: ["stomach ulcers or bleeding", "asthma", "kidney, liver or heart problems", "high blood pressure", "pregnancy"],
    onset_information: "For pain, many people notice an effect within 20 to 30 minutes.",
    duration_information: "Effects on pain typically last around 4 to 6 hours.",
    treatment_duration: null,
    sources: [nhs("ibuprofen-for-adults"), dailymed("ibuprofen")],
    last_verified_date: CURATED,
  },
  {
    medicine_id: "amoxicillin",
    generic_name: "Amoxicillin",
    brand_name: ["Amoxil", "Mox"],
    aliases: ["amoxicillin", "amoxycillin", "amoxil", "amox", "mox"],
    active_ingredients: ["Amoxicillin (as trihydrate)"],
    inactive_ingredients: INACTIVE_NOTE,
    common_strengths: ["250 mg", "500 mg", "125 mg/5 ml"],
    dosage_forms: ["Capsule", "Tablet", "Oral suspension"],
    therapeutic_class: "Antibiotic (penicillin class)",
    indications: ["Certain bacterial infections, such as some chest, ear, throat and urinary infections"],
    mechanism: {
      simple: "Helps stop certain bacteria from building their protective outer wall, so they can't survive.",
      detailed: "Beta-lactam antibiotic that binds penicillin-binding proteins and inhibits bacterial cell-wall peptidoglycan cross-linking, leading to cell lysis.",
    },
    common_side_effects: ["Nausea", "Diarrhoea"],
    important_side_effects: ["Diarrhoea that is severe, watery or contains blood", "Yellowing of skin or eyes", "Unusual bruising"],
    serious_warnings: ["Allergic reaction: rash, swelling of the face, lips or throat, wheezing or difficulty breathing"],
    food_interactions: [],
    alcohol: null,
    condition_warnings: ["a previous allergic reaction to penicillin or another antibiotic", "kidney problems"],
    onset_information: "Many people start to feel better within a few days.",
    duration_information: null,
    treatment_duration: "Courses are usually short. Complete the course exactly as prescribed.",
    sources: [nhs("amoxicillin"), dailymed("amoxicillin")],
    last_verified_date: CURATED,
  },
  {
    medicine_id: "metformin",
    generic_name: "Metformin",
    brand_name: ["Glucophage", "Glycomet"],
    aliases: ["metformin", "glucophage", "glycomet", "metformine"],
    active_ingredients: ["Metformin hydrochloride"],
    inactive_ingredients: INACTIVE_NOTE,
    common_strengths: ["500 mg", "850 mg", "1000 mg"],
    dosage_forms: ["Tablet", "Extended-release tablet", "Oral solution"],
    therapeutic_class: "Blood-glucose-lowering medicine (biguanide)",
    indications: ["Type 2 diabetes"],
    mechanism: {
      simple: "Helps lower blood sugar by reducing sugar released by the liver and helping the body use insulin better.",
      detailed: "Decreases hepatic gluconeogenesis, reduces intestinal glucose absorption and improves peripheral insulin sensitivity; partly mediated through AMP-activated protein kinase (AMPK).",
    },
    common_side_effects: ["Nausea", "Diarrhoea", "Stomach ache", "Loss of appetite", "Metallic taste"],
    important_side_effects: ["Persistent vomiting or diarrhoea (risk of dehydration)"],
    serious_warnings: ["Signs of lactic acidosis: severe tiredness, muscle pain, fast breathing, feeling very cold, stomach pain"],
    food_interactions: ["Usually taken with or after a meal to reduce stomach side effects."],
    alcohol: "Heavy alcohol use increases the risk of lactic acidosis.",
    condition_warnings: ["kidney problems", "liver problems", "heart failure", "an upcoming operation or scan with contrast dye"],
    onset_information: "Effects on blood sugar build up over days to weeks.",
    duration_information: null,
    treatment_duration: "Often a long-term medicine, as decided by your doctor.",
    sources: [nhs("metformin"), dailymed("metformin")],
    last_verified_date: CURATED,
  },
  {
    medicine_id: "atorvastatin",
    generic_name: "Atorvastatin",
    brand_name: ["Lipitor", "Atorva"],
    aliases: ["atorvastatin", "lipitor", "atorva"],
    active_ingredients: ["Atorvastatin calcium"],
    inactive_ingredients: INACTIVE_NOTE,
    common_strengths: ["10 mg", "20 mg", "40 mg", "80 mg"],
    dosage_forms: ["Tablet"],
    therapeutic_class: "Cholesterol-lowering medicine (statin)",
    indications: ["High cholesterol", "Reducing the risk of heart attack and stroke"],
    mechanism: {
      simple: "Helps lower cholesterol by reducing how much cholesterol the liver makes.",
      detailed: "Competitive inhibitor of HMG-CoA reductase, the rate-limiting enzyme of cholesterol synthesis, which up-regulates hepatic LDL receptors and lowers LDL cholesterol.",
    },
    common_side_effects: ["Headache", "Nosebleeds", "Sore throat", "Muscle or joint aches", "Indigestion"],
    important_side_effects: ["Unexplained muscle pain, tenderness or weakness"],
    serious_warnings: ["Muscle pain with dark urine or fever", "Yellowing of skin or eyes", "Allergic reaction"],
    food_interactions: ["Drinking large amounts of grapefruit juice can increase the level of this medicine in the blood."],
    alcohol: "Heavy alcohol use may increase the risk of liver problems.",
    condition_warnings: ["liver problems", "muscle problems", "heavy alcohol use", "pregnancy or breastfeeding"],
    onset_information: "Cholesterol levels usually start to fall within a few weeks.",
    duration_information: null,
    treatment_duration: "Often a long-term medicine, as decided by your doctor.",
    sources: [nhs("atorvastatin"), dailymed("atorvastatin")],
    last_verified_date: CURATED,
  },
  {
    medicine_id: "amlodipine",
    generic_name: "Amlodipine",
    brand_name: ["Norvasc", "Amlong"],
    aliases: ["amlodipine", "norvasc", "amlong", "amlo"],
    active_ingredients: ["Amlodipine (as besilate)"],
    inactive_ingredients: INACTIVE_NOTE,
    common_strengths: ["2.5 mg", "5 mg", "10 mg"],
    dosage_forms: ["Tablet", "Oral liquid"],
    therapeutic_class: "Blood-pressure medicine (calcium channel blocker)",
    indications: ["High blood pressure", "Certain types of angina (chest pain)"],
    mechanism: {
      simple: "Helps relax and widen blood vessels, which makes it easier for blood to flow.",
      detailed: "Dihydropyridine calcium channel blocker that inhibits L-type calcium influx into vascular smooth muscle, causing peripheral arterial vasodilation.",
    },
    common_side_effects: ["Headache", "Flushing", "Swollen ankles", "Dizziness", "Tiredness"],
    important_side_effects: ["Fast or irregular heartbeat", "Worsening chest pain"],
    serious_warnings: ["Chest pain that does not go away", "Allergic reaction"],
    food_interactions: [],
    alcohol: "Alcohol may increase the blood-pressure-lowering effect and dizziness.",
    condition_warnings: ["liver problems", "heart failure or a recent heart attack", "pregnancy or breastfeeding"],
    onset_information: "It may take a few weeks for the full effect on blood pressure.",
    duration_information: null,
    treatment_duration: "Often a long-term medicine, as decided by your doctor.",
    sources: [nhs("amlodipine"), dailymed("amlodipine")],
    last_verified_date: CURATED,
  },
  {
    medicine_id: "omeprazole",
    generic_name: "Omeprazole",
    brand_name: ["Prilosec", "Losec", "Omez"],
    aliases: ["omeprazole", "prilosec", "losec", "omez"],
    active_ingredients: ["Omeprazole"],
    inactive_ingredients: INACTIVE_NOTE,
    common_strengths: ["10 mg", "20 mg", "40 mg"],
    dosage_forms: ["Capsule", "Tablet", "Oral suspension"],
    therapeutic_class: "Stomach-acid reducer (proton pump inhibitor)",
    indications: ["Heartburn and acid reflux", "Stomach ulcers", "Protecting the stomach with some other medicines"],
    mechanism: {
      simple: "Reduces the amount of acid the stomach makes.",
      detailed: "Irreversibly inhibits the H+/K+-ATPase (proton pump) of gastric parietal cells, blocking the final step of acid secretion.",
    },
    common_side_effects: ["Headache", "Stomach pain", "Diarrhoea or constipation", "Nausea", "Wind"],
    important_side_effects: ["Diarrhoea that does not stop", "Joint pain with a rash"],
    serious_warnings: ["Allergic reaction", "Black or bloody stools or vomiting blood"],
    food_interactions: ["Usually taken before a meal, often in the morning."],
    alcohol: "Alcohol can increase stomach acid and may worsen symptoms.",
    condition_warnings: ["liver problems", "low magnesium levels", "osteoporosis"],
    onset_information: "May take 2 to 3 days to start working and up to about 4 weeks for full effect.",
    duration_information: null,
    treatment_duration: null,
    sources: [nhs("omeprazole"), dailymed("omeprazole")],
    last_verified_date: CURATED,
  },
  {
    medicine_id: "cetirizine",
    generic_name: "Cetirizine",
    brand_name: ["Zyrtec", "Cetzine"],
    aliases: ["cetirizine", "zyrtec", "cetzine", "cetrizine"],
    active_ingredients: ["Cetirizine hydrochloride"],
    inactive_ingredients: INACTIVE_NOTE,
    common_strengths: ["10 mg", "5 mg/5 ml"],
    dosage_forms: ["Tablet", "Oral liquid"],
    therapeutic_class: "Antihistamine",
    indications: ["Hay fever and allergy symptoms", "Itchy skin rashes such as hives"],
    mechanism: {
      simple: "Blocks histamine, a chemical the body releases during an allergic reaction.",
      detailed: "Selective peripheral histamine H1-receptor antagonist (second-generation antihistamine) with limited penetration into the brain.",
    },
    common_side_effects: ["Drowsiness or tiredness", "Dry mouth", "Headache"],
    important_side_effects: ["Difficulty passing urine"],
    serious_warnings: ["Allergic reaction"],
    food_interactions: [],
    alcohol: "Alcohol may increase drowsiness.",
    condition_warnings: ["kidney problems", "epilepsy", "difficulty passing urine"],
    onset_information: "Usually starts to work within about an hour.",
    duration_information: "One dose usually lasts about 24 hours.",
    treatment_duration: null,
    sources: [nhs("cetirizine"), dailymed("cetirizine")],
    last_verified_date: CURATED,
  },
  {
    medicine_id: "warfarin",
    generic_name: "Warfarin",
    brand_name: ["Coumadin", "Marevan"],
    aliases: ["warfarin", "coumadin", "marevan", "warf"],
    active_ingredients: ["Warfarin sodium"],
    inactive_ingredients: INACTIVE_NOTE,
    common_strengths: ["1 mg", "3 mg", "5 mg"],
    dosage_forms: ["Tablet"],
    therapeutic_class: "Anticoagulant (blood thinner)",
    indications: ["Preventing and treating harmful blood clots"],
    mechanism: {
      simple: "Makes the blood take longer to clot by reducing clotting factors that depend on vitamin K.",
      detailed: "Inhibits vitamin K epoxide reductase (VKORC1), reducing synthesis of vitamin K-dependent clotting factors II, VII, IX and X and proteins C and S.",
    },
    common_side_effects: ["Bleeding more easily, such as nosebleeds or bleeding gums", "Bruising"],
    important_side_effects: ["Unusual or heavy bleeding", "Blood in urine", "Heavy periods"],
    serious_warnings: ["Vomiting blood, black stools, or bleeding that won't stop", "A severe headache or a head injury"],
    food_interactions: [
      "Sudden changes in foods high in vitamin K (such as leafy green vegetables) can affect how warfarin works.",
      "Cranberry and grapefruit juice may affect warfarin.",
    ],
    alcohol: "Alcohol can affect how warfarin works and increase bleeding risk.",
    condition_warnings: ["a bleeding disorder or recent bleeding", "liver or kidney problems", "pregnancy", "an upcoming operation or dental treatment"],
    onset_information: "Takes several days to reach its full effect; blood tests are used to monitor it.",
    duration_information: null,
    treatment_duration: "Decided by your doctor based on your blood tests and condition.",
    sources: [nhs("warfarin"), dailymed("warfarin")],
    last_verified_date: CURATED,
  },
  {
    medicine_id: "aspirin",
    generic_name: "Aspirin",
    brand_name: ["Disprin", "Ecosprin", "Bayer Aspirin"],
    aliases: ["aspirin", "acetylsalicylic acid", "asa", "disprin", "ecosprin"],
    active_ingredients: ["Acetylsalicylic acid"],
    inactive_ingredients: INACTIVE_NOTE,
    common_strengths: ["75 mg", "81 mg", "300 mg"],
    dosage_forms: ["Tablet", "Dispersible tablet", "Gastro-resistant tablet"],
    therapeutic_class: "Antiplatelet medicine / NSAID (depending on dose)",
    indications: ["Low dose: helping prevent heart attacks and strokes in some people", "Higher dose: pain and fever"],
    mechanism: {
      simple: "At low doses, helps stop blood cells called platelets from sticking together to form clots.",
      detailed: "Irreversibly acetylates cyclo-oxygenase (COX-1), blocking platelet thromboxane A2 production for the life of the platelet.",
    },
    common_side_effects: ["Indigestion", "Bleeding or bruising more easily"],
    important_side_effects: ["Black or bloody stools", "Ringing in the ears"],
    serious_warnings: ["Vomiting blood", "Allergic reaction or asthma worsening", "Bleeding that won't stop"],
    food_interactions: ["Often taken with or after food to reduce stomach irritation."],
    alcohol: "Alcohol may increase the risk of stomach bleeding.",
    condition_warnings: ["stomach ulcers or bleeding", "asthma", "a bleeding disorder", "kidney or liver problems"],
    onset_information: null,
    duration_information: null,
    treatment_duration: null,
    sources: [nhs("low-dose-aspirin"), dailymed("aspirin")],
    last_verified_date: CURATED,
  },
];

const DDI = (q: string): SourceRef => ({ name: "MedlinePlus Drug Information (NLM)", url: `https://medlineplus.gov/druginfo/meds/${q}` });

export const INTERACTIONS: InteractionRecord[] = [
  {
    medicine_a: "ibuprofen",
    medicine_b: "warfarin",
    severity: "major",
    interaction_type: "Increased bleeding risk",
    interaction_description: "NSAIDs such as ibuprofen can irritate the stomach lining and affect platelets, while warfarin slows blood clotting.",
    clinical_concern: "Taken together, the risk of bleeding, including stomach bleeding, may be higher.",
    sources: [nhs("warfarin"), DDI("a682277.html")],
    last_verified_date: CURATED,
  },
  {
    medicine_a: "aspirin",
    medicine_b: "warfarin",
    severity: "major",
    interaction_type: "Increased bleeding risk",
    interaction_description: "Both medicines affect how blood clots, through different pathways.",
    clinical_concern: "The combined effect may increase the risk of bleeding. Sometimes both are prescribed deliberately with monitoring.",
    sources: [nhs("warfarin")],
    last_verified_date: CURATED,
  },
  {
    medicine_a: "aspirin",
    medicine_b: "ibuprofen",
    severity: "moderate",
    interaction_type: "Reduced antiplatelet effect / stomach irritation",
    interaction_description: "Ibuprofen may interfere with the clot-preventing effect of low-dose aspirin, and both can irritate the stomach.",
    clinical_concern: "Possible reduced protection from low-dose aspirin and a higher risk of stomach bleeding.",
    sources: [nhs("low-dose-aspirin"), nhs("ibuprofen-for-adults")],
    last_verified_date: CURATED,
  },
  {
    medicine_a: "paracetamol",
    medicine_b: "warfarin",
    severity: "moderate",
    interaction_type: "Possible change in blood-thinning effect",
    interaction_description: "Regular use of paracetamol over several days may increase the effect of warfarin.",
    clinical_concern: "Blood-clotting test results (INR) may change.",
    sources: [nhs("warfarin")],
    last_verified_date: CURATED,
  },
  {
    medicine_a: "amoxicillin",
    medicine_b: "warfarin",
    severity: "moderate",
    interaction_type: "Possible change in blood-thinning effect",
    interaction_description: "Some antibiotics, including amoxicillin, have been reported to alter the effect of warfarin.",
    clinical_concern: "Blood-clotting test results (INR) may change during the antibiotic course.",
    sources: [nhs("warfarin")],
    last_verified_date: CURATED,
  },
  {
    medicine_a: "omeprazole",
    medicine_b: "warfarin",
    severity: "moderate",
    interaction_type: "Possible change in blood-thinning effect",
    interaction_description: "Omeprazole may affect how the body processes warfarin.",
    clinical_concern: "Blood-clotting test results (INR) may change.",
    sources: [nhs("omeprazole")],
    last_verified_date: CURATED,
  },
  {
    medicine_a: "amlodipine",
    medicine_b: "ibuprofen",
    severity: "minor",
    interaction_type: "Possible reduced blood-pressure-lowering effect",
    interaction_description: "NSAIDs such as ibuprofen can cause the body to retain fluid and may raise blood pressure.",
    clinical_concern: "May reduce how well blood-pressure medicines work, especially with regular use.",
    sources: [nhs("amlodipine")],
    last_verified_date: CURATED,
  },
];
